"""
Django settings for codestar project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# Load environment variables from env.py when present (local development only).
if os.path.isfile(os.path.join(BASE_DIR, "env.py")):
    import env




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.environ.get("SECRET_KEY")        
# SECURITY WARNING: don't run with debug turned on in production!
# Reads the DEBUG environment variable. Set DEBUG="True" in your local
# env.py for development; production leaves it unset, so it defaults to False.
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ['.herokuapp.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    #user authentication
    'django.contrib.sites',# a built-in Django package
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    #Adding a comment form
    'crispy_forms',
    'crispy_bootstrap5',

    'django_summernote',
    'cloudinary',
    'blog',
    'about',
]

#user authentication; setting the site and home page after login and logout
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#Adding a comment form
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Map Django message levels to Bootstrap alert classes so {{ message.tags }}
# renders as e.g. "alert-success" (green) instead of just "success".
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise serves static files directly from Django in production.
    # It MUST go right after SecurityMiddleware and before everything else,
    # so it can intercept static file requests early and serve them efficiently.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #user authentication; adds additional functionality 
    'allauth.account.middleware.AccountMiddleware',
]

#user authentication; not using email verification in this project
ACCOUNT_EMAIL_VERIFICATION = 'none'

ROOT_URLCONF = 'codestar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codestar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}
#Automate test
if 'test' in sys.argv:
    DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'


CSRF_TRUSTED_ORIGINS = [
    "https://*.codeinstitute-ide.net/",
    "https://*.herokuapp.com"
   
]

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
# Absolute filesystem path where `collectstatic` will gather ALL static files
# (your app's + Django admin's + any installed package's) into one folder,
# ready to be served in production.
#STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Tells Django (4.2+) which storage engine to use for static files.
# CompressedManifestStaticFilesStorage:
#   - Compresses files (gzip) for faster delivery
#   - Adds a hash to each filename (e.g. style.a1b2c3.css) so browsers
#     cache files safely and reliably bust the cache when files change
# NOTE: defining STORAGES replaces Django's defaults entirely, so the
# "default" entry (used for FileField/media uploads, e.g. by
# django-summernote) MUST be included alongside "staticfiles" — otherwise
# Django raises InvalidStorageError: Could not find config for 'default'.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user-uploaded content, e.g. images added via the Summernote
# editor). MEDIA_ROOT is the folder on disk where uploads are saved;
# MEDIA_URL is the URL prefix the browser uses to request them.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configure Django's logging so that error tracebacks are printed
# to the console (stdout) instead of being silently dropped or
# emailed to admins (which isn't configured here).
# Heroku captures anything written to stdout/stderr and shows it
# in `heroku logs`, so this makes 500 errors visible there.
LOGGING = {
    'version': 1,  # required key, always 1 for Django's logging config schema

    # Keep Django's default loggers (e.g. for security, requests) active
    # instead of disabling them when we define our own.
    'disable_existing_loggers': False,

    'handlers': {
        # A handler defines WHERE log messages go.
        # 'console' sends them to stdout/stderr, which Heroku logs.
        'console': {
            'class': 'logging.StreamHandler',
        },
    },

    'loggers': {
        # The 'django' logger catches framework-level events,
        # including unhandled exceptions in views (like our 500 error).
        'django': {
            'handlers': ['console'],  # send these logs to the console handler above
            'level': 'ERROR',         # only log ERROR and above (ignores INFO/DEBUG noise)
            'propagate': True,        # let messages also bubble up to any parent loggers
        },
    },
}